name: Claude Args Example

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: "Prompt for Claude"
        required: true
        type: string

jobs:
  claude-with-custom-args:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Claude with custom arguments
        uses: anthropics/claude-code-action@v1
        with:
          mode: agent
          prompt: ${{ github.event.inputs.prompt }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

          # New claudeArgs input allows direct CLI argument control
          # Order: -p [claudeArgs] [legacy options] [BASE_ARGS]
          # Note: BASE_ARGS (--verbose --output-format stream-json) cannot be overridden
          claude_args: |
            --max-turns 15
            --model claude-3-opus-20240229
            --allowedTools Edit,Read,Write,Bash
            --disallowedTools WebSearch
            --system-prompt "You are a senior engineer focused on code quality"
