name: Auto review PRs

on:
  pull_request:
    types: [opened]

jobs:
  auto-review:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Auto review PR
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prompt: |
            Please review this PR and provide comprehensive feedback.
            
            Focus on:
            - Code quality and best practices
            - Potential bugs or issues
            - Suggestions for improvements
            - Overall architecture and design decisions
            - Documentation consistency
            
            After completing your review, write it to a file then post it as a PR comment using these commands:
            
            1. First save your review to a file:
            cat > /tmp/pr-review.md << 'EOF'
            YOUR_REVIEW_CONTENT_HERE
            EOF
            
            2. Then post it:
            gh pr comment ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --body-file /tmp/pr-review.md
            
            Make sure to format your review nicely with markdown headers, bullet points, and code blocks.
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          claude_args: "--allowedTools Bash(gh pr comment:*),Read,Grep,Glob"
